// ResetError
export const RESET_ERROR = 'RESET_ERROR';

// User.Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
// User.Get
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';
// User.List
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';
// User.Put
export const USER_PUT_REQUEST = 'USER_PUT_REQUEST';
export const USER_PUT_SUCCESS = 'USER_PUT_SUCCESS';
export const USER_PUT_FAILURE = 'USER_PUT_FAILURE';
// User.Delete
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';
// Logout
export const LOGOUT = 'LOGOUT';

// Exchange.Types
export const EXCHANGE_TYPES_REQUEST = 'EXCHANGE_TYPES_REQUEST';
export const EXCHANGE_TYPES_SUCCESS = 'EXCHANGE_TYPES_SUCCESS';
export const EXCHANGE_TYPES_FAILURE = 'EXCHANGE_TYPES_FAILURE';
// Exchange.List
export const EXCHANGE_LIST_REQUEST = 'EXCHANGE_LIST_REQUEST';
export const EXCHANGE_LIST_SUCCESS = 'EXCHANGE_LIST_SUCCESS';
export const EXCHANGE_LIST_FAILURE = 'EXCHANGE_LIST_FAILURE';
// Exchange.Put
export const EXCHANGE_PUT_REQUEST = 'EXCHANGE_PUT_REQUEST';
export const EXCHANGE_PUT_SUCCESS = 'EXCHANGE_PUT_SUCCESS';
export const EXCHANGE_PUT_FAILURE = 'EXCHANGE_PUT_FAILURE';
// Exchange.Delete
export const EXCHANGE_DELETE_REQUEST = 'EXCHANGE_DELETE_REQUEST';
export const EXCHANGE_DELETE_SUCCESS = 'EXCHANGE_DELETE_SUCCESS';
export const EXCHANGE_DELETE_FAILURE = 'EXCHANGE_DELETE_FAILURE';

// Algorithm.List
export const ALGORITHM_LIST_REQUEST = 'ALGORITHM_LIST_REQUEST';
export const ALGORITHM_LIST_SUCCESS = 'ALGORITHM_LIST_SUCCESS';
export const ALGORITHM_LIST_FAILURE = 'ALGORITHM_LIST_FAILURE';
// Algorithm.Put
export const ALGORITHM_PUT_REQUEST = 'ALGORITHM_PUT_REQUEST';
export const ALGORITHM_PUT_SUCCESS = 'ALGORITHM_PUT_SUCCESS';
export const ALGORITHM_PUT_FAILURE = 'ALGORITHM_PUT_FAILURE';
// Algorithm.Delete
export const ALGORITHM_DELETE_REQUEST = 'ALGORITHM_DELETE_REQUEST';
export const ALGORITHM_DELETE_SUCCESS = 'ALGORITHM_DELETE_SUCCESS';
export const ALGORITHM_DELETE_FAILURE = 'ALGORITHM_DELETE_FAILURE';
// Algorithm.Cache
export const ALGORITHM_CACHE = 'ALGORITHM_CACHE';

// Trader.List
export const TRADER_LIST_REQUEST = 'TRADER_LIST_REQUEST';
export const TRADER_LIST_SUCCESS = 'TRADER_LIST_SUCCESS';
export const TRADER_LIST_FAILURE = 'TRADER_LIST_FAILURE';
// Trader.Put
export const TRADER_PUT_REQUEST = 'TRADER_PUT_REQUEST';
export const TRADER_PUT_SUCCESS = 'TRADER_PUT_SUCCESS';
export const TRADER_PUT_FAILURE = 'TRADER_PUT_FAILURE';
// Trader.Delete
export const TRADER_DELETE_REQUEST = 'TRADER_DELETE_REQUEST';
export const TRADER_DELETE_SUCCESS = 'TRADER_DELETE_SUCCESS';
export const TRADER_DELETE_FAILURE = 'TRADER_DELETE_FAILURE';
// Trader.Switch
export const TRADER_SWITCH_REQUEST = 'TRADER_SWITCH_REQUEST';
export const TRADER_SWITCH_SUCCESS = 'TRADER_SWITCH_SUCCESS';
export const TRADER_SWITCH_FAILURE = 'TRADER_SWITCH_FAILURE';
// Trader.Cache
export const TRADER_CACHE = 'TRADER_CACHE';

// Log.List
export const LOG_LIST_REQUEST = 'LOG_LIST_REQUEST';
export const LOG_LIST_SUCCESS = 'LOG_LIST_SUCCESS';
export const LOG_LIST_FAILURE = 'LOG_LIST_FAILURE';
