// ResetError
export const RESET_ERROR = 'RESET_ERROR';

// User.Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
// User.Get
export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';
// User.List
export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';
// User.Put
export const USER_PUT_REQUEST = 'USER_PUT_REQUEST';
export const USER_PUT_SUCCESS = 'USER_PUT_SUCCESS';
export const USER_PUT_FAILURE = 'USER_PUT_FAILURE';
// Logout
export const LOGOUT = 'LOGOUT';
